// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJAEOXqHJ0SuaUTT-iXEcPwY2amfKkDqs',
    appId: '1:400170808749:web:c3def2d7f88e952e201d24',
    messagingSenderId: '35092147805',
    projectId: 'gotu-2c49e',
    authDomain: 'gotu-2c49e.firebaseapp.com',
    storageBucket: 'gotu-2c49e.appspot.com',
    measurementId: 'G-QXXR94SL3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJAEOXqHJ0SuaUTT-iXEcPwY2amfKkDqs',
    appId: '1:35092147805:android:5681b1f06493d506fd67b4',
    messagingSenderId: '35092147805',
    projectId: 'gotu-2c49e',
    storageBucket: 'gotu-2c49e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJAEOXqHJ0SuaUTT-iXEcPwY2amfKkDqs',
    appId: '1:400170808749:ios:a75aee5fcf4d1b78201d24',
    messagingSenderId: '35092147805',
    projectId: 'gotu-2c49e',
    storageBucket: 'gotu-2c49e.appspot.com',
    iosClientId: '400170808749-qqbcat7s51eto9p7ug024t7khkkkon7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.gotuappv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJAEOXqHJ0SuaUTT-iXEcPwY2amfKkDqs',
    appId: '1:400170808749:ios:cd4b9a904b914a82201d24',
    messagingSenderId: '35092147805',
    projectId: 'gotu-2c49e',
    storageBucket: 'gotu-2c49e.appspot.com',
    iosClientId: '400170808749-dpc93llg7ndiq93n789654id40qksb84.apps.googleusercontent.com',
    iosBundleId: 'com.example.gotuappv1.RunnerTests',
  );
}
